name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      with:
        toolchain: nightly
        components: rust-docs
    - run: rustup default nightly
            
    - name: Install mdbook
      run: cargo install mdbook
      
    - name: Run tests
      run: mdbook test
      
    # - name: Cache/Restore linkcheck
    #   id: cache
    #   uses: actions/cache@v4.0.2
    #   with:
    #     path: linkchecker
    #     key: linkchecker-${{ runner.os }}

    - name: Install linkcheck and Check links
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -sSLo linkcheck.sh \
          https://raw.githubusercontent.com/rust-lang/rust/master/src/tools/linkchecker/linkcheck.sh
          sh linkcheck.sh --all nomicon

    # - name: Check links
    #   if: steps.cache.outputs.cache-hit == 'true'
    #   run: |
    #     cd linkchecker
    #     cargo run --release linkcheck
